### ISSUE TITLE
Create New System for Member Voucher Codes

### ISSUE THREAD

**Issue by S-Willis** [EdinburghUniversityTheatreCompany/black_lightning#24]
I will not mention the current system for sending out voucher codes. It does work, but it is sub-optimal.

Requirements:

- Codes must be a defined length of alphanumeric characters long, and prefixed with MEM.
- Must be able to press a button to regenerate a member's code.
- Must be able to press a button to disable (remove from active list) a code.
- Codes must be non-colliding.
- There must exist a list of active member codes
- A user's code should appear on their User Page, but only to that user. 

Other Notes:

- Probably generate a list of 15-20000 codes (which will be non sequential) and assign them to users sequentially (wrt. the list).
- Create a model and associate it with person.

**Comment by mickzijdel** [comment]
No longer use voucher codes
