### ISSUE TITLE
Upgrade Webpacker

### ISSUE THREAD

**Issue by mickzijdel** [EdinburghUniversityTheatreCompany/black_lightning#71]
Webpacker has been retired by the Ruby on Rails project starting with Rails 7.0. However, it will still receive security upgrades and everything still works fine. Because Rails has a tendency to update the asset pipeline every major version, it is probably not worth it to upgrade it right now.

In the future, we have two main options, but there might be more
- Upgrade to [Shakapacker](https://github.com/shakacode/shakapacker), which is Webpacker's spiritual successor.
- Use [Import Maps](https://github.com/rails/importmap-rails) and [CSS Bundling](https://github.com/rails/cssbundling-rails), which is the default way to do it for Rails 7.0. This would involve revamping some of the asset pipeline, and is also a good time to fully get rid of Sprockets which was the asset pipeline before Rails 6.0

**Comment by AlexanderMohan** [comment]
closes #92

my preferred move would be jsbundling, will write more here soon
